
name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Help
      run: |
        docker build --help
        apt-get update -y
        apt-get install -y gperf
    - name: Fetch dependencies
      run: |
        autoconf --version
        cd ci-tools

        wget -O iverilog-11_0.tar.gz https://github.com/steveicarus/iverilog/archive/refs/tags/v11_0.tar.gz
        tar xvzf iverilog-11_0.tar.gz
        echo "Change directory"
        cd iverilog-11_0
        echo "Autoconf"
        /bin/sh ./autoconf.sh
        echo "Change back"
        cd ..
        echo "Pack"
        tar czf iverilog-11_0.tar.gz iverilog-11_0

        wget -O verilator-4.204.tar.gz https://github.com/verilator/verilator/archive/refs/tags/v4.204.tar.gz
        tar xvzf verilator-4.204.tar.gz
        cd verilator-4.204
        /bin/sh ./autoconf
        cd ..
        tar czf verilator-4.204.tar.gz verilator-4.204

    - name: Build Tool-Build Image
      run: |
        docker build -t tblink-rpc-ci-tools-build ci-tools-build
    - name: Build Tools
      run: |
        docker run --volume `pwd`/ci-tools:/ci-tools tblink-rpc-ci-tools-build /ci-tools/build.sh
    - name: Unpack Tools
      run: |
        cd ci-tools
        tar xvzf tools.tar.gz
    - name: Build Tools Image
      run: |
        docker build -t tblink-rpc-ci-tools ci-tools
    - name: Push Image
      run: |
        echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u mballance --password-stdin
        docker tag tblink-rpc-ci-tools:latest ghcr.io/tblink-rpc/tblink-rpc-ci-tools:latest
        docker push ghcr.io/tblink-rpc/tblink-rpc-ci-tools:latest

